snippets:

    # git
    - name: g
      keyword: g
      snippet: git
    
    - name: git s
      keyword: s
      snippet: status
      context:
        lbuffer: ^git\s
    
    - name: git a
      keyword: a
      snippet: add
      context:
        lbuffer: ^git\s
    
    - name: git aa
      keyword: aa
      snippet: add --all
      context:
        lbuffer: ^git\s

    - name: git l
      keyword: l
      snippet: log --oneline
      context:
        lbuffer: ^git\s
    
    - name: git c
      keyword: c
      snippet: commit
      context:
        lbuffer: ^git\s
    
    - name: git commit message
      keyword: gcim
      snippet: git commit -m '{{commit_message}}'
    
    - name: git push origin hoge
      keyword: gpo
      snippet: git push origin {{branch}}
    
    - name: git pull origin hoge
      keyword: gplo
      snippet: git pull origin {{branch}}
    
    - name: claude
      keyword: cl
      snippet: claude
    
    - name: worktree
      keyword: wt
      snippet: git worktree add -b {{branch}} ../{{branch}}

completions:
  - name: git switch branch
    patterns:
      - "^git switch $"
    sourceCommand: "git branch --format='%(refname:short)'"
    options:
      --prompt: "'Branch> '"
      --preview: "git log --oneline --graph --decorate --color=always -20 {}"
  
  - name: kill pid
    patterns:
      - "^kill( .*)? $"
    sourceCommand: "LANG=C ps -ef"
    options:
      --header-lines: 1
    callback: "awk '{print $2}'"